final_project/2-code/MovieHunter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from . import views
from django.urls import path, include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('insta/', include('Insta.urls')),

    url(r'^movie/', include('movie.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^poll/', include('poll.urls', namespace="poll")),
    url(r'^$', views.index, name='index'),
    url(r'.*', lambda request: render(request, '404.html'), name='404'),
]

final_project/2-code/poll/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views as views
from poll.views import PollCreateView

app_name = 'poll'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex : /poll/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^detail/', views.detail, name='detail'),
    # ex : /poll/5/results/
    url(r'^(?P<question_id>[0-9]+)/results', views.results, name='results'),
    # ex : /poll/5/vote
    #path('blog/page<int:num>/', views.vote),
    url(r'^(?P<question_id>[0-9]+)/vote', views.vote, name='vote'),
    url('new/', views.PollCreateView, name='newpoll'),

]
#   url(r'^register/', views.user_register, name='register'),

final_project/2-code/poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text



# choice
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text



# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __unicode__(self):
        return self.username

final_project/2-code/poll/views.py
# coding=utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Question, Choice
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import CreateView

# Create your views here.
# 首页展示所有问题
@csrf_protect
def index(request):
    # latest_question_list2 = Question.objects.order_by('-pub_data')[:2]
    latest_question_list = Question.objects.all()
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)


# 查看所有问题
@csrf_protect
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/detail.html', {'question': question})


# 查看投票结果
@csrf_protect
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})


# 选择投票
@csrf_protect
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(p.id,)))


class PollCreateView(CreateView):
    model = Question
    template_name = 'poll/make_poll.html'
    fields = '__all__' 

final_project/2-code/poll/templates/poll/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'poll:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

final_project/2-code/poll/templates/poll/index.html
<header>
    <div>
        <!-- <li>
            <a href="{% url 'poll:newpoll' %}"> Set up a new poll </a>
        </li> -->

        <li>
            <a href="/admin/poll/question/add/"> Set up a new poll </a>
        </li>

        <li>
            <a href="/admin/poll/question/"> Edit the poll </a>
        </li>

    </div>
</header>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}



 

final_project/2-code/poll/templates/poll/make_poll.html
<h1> Set up a new poll </h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Save </button>
</form>

final_project/2-code/poll/templates/poll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>